language: java
jdk:
 - openjdk12
env:
 global:
  - GITHUB_ACTOR=araqnid
  - secure: "Suu9aG7/qszm3d/94gqbdv6Y3+5sWX+Ik+1Z43WArDoQNFQvlaZpzO91h2YVognjcRsUbyH6B+PUqgloEhngWMCVmRrm9mJSZtfXHXM90OOvhbq9DVrPIwCsrua7vQhkSgeL7V8mr39zH01yN+QCp6EYo9cG3gh43iUU+1BECTVdCgOSe9kO/dFoqfL52D7KArHzjlfoy+JdUbIbICKa12uv6KbqGAJYUBcwE9WzrrWnVMcECkmPL3WITqP0I2pCmnzlVzLvY8CVQX+e/CJEWPZ1Ii0J2lrQjJWD/xY01P3fRF0/P6JOvrLNVLqB9+cLTtW8lW3GF+h+jT+hOZ7JvKVCJ9q/SP3CzVHcT2Rmc4SYZ63XvvNkMQKRmPvE8ExJXkkJhxgr3tmw8rXd3vf1afTAxC/L4ywcAbNB148I+0JE0DScHHDAYwApR9VprVwdN10aat9a5huOdhCURYkMATAoHI6JeQWfClwXAq0YagVnQn/ck9LCMe7OoY0sy64lq3YIzXgZPbw1YV3V0xg22N9UC9jSdjEXi/V/fRmKYzeSH5+FsxfPrjlGCMM4JgclDRAmcWCCN4YZHYk6ZRxg3BkflpDQBAKNCLszUPLsYFJ+pWJwghGqi5VOcf8sBRi1Vvu+HTztj8F8zHKfHtm5bOm52mynBNXmTjA0JGEHCro="
