#!/bin/sh

set -e

cd "$(dirname "$0")/"

gradle() {
  ./gradlew "$@"
}

tagged_as=$(git describe --tags)
if expr "$tagged_as" : 'v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; then
  echo "$0: current version $tagged_as is already a release version" >&2
  exit 1
fi

version_patchnr=$(expr "$tagged_as" : 'v[0-9][0-9]*\.[0-9][0-9]*\.\([0-9][0-9]*\)-')
if [ -z "$version_patchnr" ]; then
  echo "$0: current version $tagged_as is not a release version and doesn't have an obvious patch scheme" >&2
  exit 1
fi

version_majmin=$(expr "$tagged_as" : 'v\([0-9][0-9]*\.[0-9][0-9]*\)\.[0-9][0-9]*')
next_patchnr=$(expr $version_patchnr + 1)
next_version="$version_majmin.$next_patchnr"

BUILD_NUMBER=$next_patchnr gradle clean build

git tag -m "Version $next_version" v$next_version

BUILD_NUMBER=$next_patchnr gradle --no-daemon bintrayUpload
