name: "Gradle Build"
on:
  push:
    paths-ignore:
      - README.md
      - docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'ui/yarn.lock'
      - uses: gradle/gradle-command-action@v2
        with:
          arguments: build
